<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="1" ignored="1" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-09-24T18:48:01 IST" name="Suite" finished-at="2024-09-24T18:48:23 IST" duration-ms="22052">
    <groups>
      <group name="ErrorHandling">
        <method signature="ErrorValidationTest.loginErrorValidation()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" name="loginErrorValidation" class="KanhaFrameworkDesign.tests.ErrorValidationTest"/>
      </group> <!-- ErrorHandling -->
      <group name="Purshase">
        <method signature="SampleTest.submitOrder(java.util.HashMap)[pri:0, instance:KanhaFrameworkDesign.tests.SampleTest@1b955cac]" name="submitOrder" class="KanhaFrameworkDesign.tests.SampleTest"/>
      </group> <!-- Purshase -->
    </groups>
    <test started-at="2024-09-24T18:48:01 IST" name="Base Test " finished-at="2024-09-24T18:48:01 IST" duration-ms="26">
    </test> <!-- Base Test  -->
    <test started-at="2024-09-24T18:48:01 IST" name="Error Validation Test " finished-at="2024-09-24T18:48:23 IST" duration-ms="22052">
      <class name="KanhaFrameworkDesign.tests.ErrorValidationTest">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:01 IST" name="launchApplication" finished-at="2024-09-24T18:48:07 IST" duration-ms="6100" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="loginErrorValidation()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:07 IST" name="loginErrorValidation" finished-at="2024-09-24T18:48:08 IST" duration-ms="1042" status="SKIP">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password..]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password..]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at KanhaFrameworkDesign.tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:228)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:08 IST" name="tearDown" finished-at="2024-09-24T18:48:09 IST" duration-ms="414" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:09 IST" name="launchApplication" finished-at="2024-09-24T18:48:10 IST" duration-ms="1718" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="loginErrorValidation()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:10 IST" name="loginErrorValidation" finished-at="2024-09-24T18:48:11 IST" duration-ms="633" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Incorrect email or password.] but found [Incorrect email or password..]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email or password..]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at KanhaFrameworkDesign.tests.ErrorValidationTest.loginErrorValidation(ErrorValidationTest.java:28)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:249)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:961)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:201)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:819)
at org.testng.TestRunner.run(TestRunner.java:619)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:481)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:58)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:840)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:11 IST" name="tearDown" finished-at="2024-09-24T18:48:12 IST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:12 IST" name="launchApplication" finished-at="2024-09-24T18:48:14 IST" duration-ms="2589" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="productErrorValidation()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:14 IST" name="productErrorValidation" finished-at="2024-09-24T18:48:23 IST" duration-ms="8752" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- productErrorValidation -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:KanhaFrameworkDesign.tests.ErrorValidationTest@61a88b8c]" started-at="2024-09-24T18:48:23 IST" name="tearDown" finished-at="2024-09-24T18:48:23 IST" duration-ms="218" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- KanhaFrameworkDesign.tests.ErrorValidationTest -->
    </test> <!-- Error Validation Test  -->
  </suite> <!-- Suite -->
</testng-results>
